### ISSUE TITLE
Issue with nested objects

### ISSUE THREAD

**Issue by fisherdarling** [ticket-bridge/hyper-durable#23]
Love the library! Thanks for releasing it :)

I keep getting a type error when I use nested objects:

```
TypeError: this is not a Date object.
        at Proxy.valueOf (<anonymous>)
```

This occurs when you have a DOI with a nested object:

```typescript
class MyDo {
  my_dates: {
    created_at: Date
  }
  
  ...
}
```

I've modified the Counter DO and tests to include a property like the above and the tests do cause an exception. Here's my fork and branch where I'm trying to fix this: https://github.com/fisherdarling/hyper-durable/tree/feat/fix-proxy-getters

Any thoughts would be much appreciated! And again, thanks for making such an awesome library :D

**Comment by TravisFrankMTG** [comment]
Hey @fisherdarling!  Thanks for checking out the library, glad you found it useful.  I just released a fix for deeply-nested object persistence, can you pull and give it a try on your scenario?

**Comment by TravisFrankMTG** [comment]
Closing due to fix
